name: Build Images
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Adjust build version
      id: embed_version
      run: |
        sed -i 's/^.*MARKER-REPLACE-LINE-IN-CI.*/echo "nats-box ${{ github.ref_name }}" >\&2/' profile.sh

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Setup Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_CLI_TOKEN }}

    - name: Get Image Tags
      id: tags
      run: |
        version=$(sed 's/^v//' <<< ${{ github.ref_name }})
        echo tags="latest,${version}" >> $GITHUB_OUTPUT

    - name: Build and Push
      uses: docker/bake-action@v5
      env:
        TAGS: "${{ steps.tags.outputs.tags }}"
        REGISTRY: "natsio"
      with:
        push: true
